// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmk1SUzDV3Ls7Lo-dhprvtDAw6XALkdQY',
    appId: '1:706675824912:web:e7ccd3f4b7cf5272d92d95',
    messagingSenderId: '706675824912',
    projectId: 'reddit-clone-ea9a0',
    authDomain: 'reddit-clone-ea9a0.firebaseapp.com',
    storageBucket: 'reddit-clone-ea9a0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHb1o03v7yo3oGEXOM4Si91m02LEgzpJA',
    appId: '1:706675824912:android:ec9139f00dcfbae3d92d95',
    messagingSenderId: '706675824912',
    projectId: 'reddit-clone-ea9a0',
    storageBucket: 'reddit-clone-ea9a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu-9q8EST1uMU6ms30ogAPRP9wUrFPTsA',
    appId: '1:706675824912:ios:447932eebc5a7934d92d95',
    messagingSenderId: '706675824912',
    projectId: 'reddit-clone-ea9a0',
    storageBucket: 'reddit-clone-ea9a0.appspot.com',
    iosBundleId: 'com.example.redditApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu-9q8EST1uMU6ms30ogAPRP9wUrFPTsA',
    appId: '1:706675824912:ios:352b3348e319bbb2d92d95',
    messagingSenderId: '706675824912',
    projectId: 'reddit-clone-ea9a0',
    storageBucket: 'reddit-clone-ea9a0.appspot.com',
    iosBundleId: 'com.example.redditApp.RunnerTests',
  );
}
